# Generated by Django 2.2.1 on 2019-10-04 19:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumchoicefield.fields
import iotrec_api.utils.thing
import location_field.models.plain
import mptt.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('iotrec_api', '0001_initial'), ('iotrec_api', '0002_auto_20190728_0858'), ('iotrec_api', '0003_user_preferences'), ('iotrec_api', '0004_auto_20190930_2023'), ('iotrec_api', '0005_auto_20191002_1647'), ('iotrec_api', '0006_auto_20191002_1710'), ('iotrec_api', '0007_auto_20191002_1715'), ('iotrec_api', '0008_auto_20191002_1723'), ('iotrec_api', '0009_auto_20191002_1724'), ('iotrec_api', '0010_auto_20191003_0722'), ('iotrec_api', '0011_auto_20191003_0724'), ('iotrec_api', '0012_category_value'), ('iotrec_api', '0013_auto_20191004_1355'), ('iotrec_api', '0014_auto_20191004_1431'), ('iotrec_api', '0015_auto_20191004_1530'), ('iotrec_api', '0016_auto_20191004_1557'), ('iotrec_api', '0017_auto_20191004_1614'), ('iotrec_api', '0018_auto_20191004_1818')]

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('text_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_alias', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('alias_owner', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='iotrec_api.Category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='iotrec_api.Category')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.CharField(default=None, max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Thing', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('type', enumchoicefield.fields.EnumChoiceField(default=iotrec_api.utils.thing.ThingType(1), enum_class=iotrec_api.utils.thing.ThingType, max_length=8)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('major_id', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('minor_id', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63)),
                ('categories', mptt.fields.TreeManyToManyField(blank=True, to='iotrec_api.Category')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('invoke_rec', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotrec_api.Thing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotrec_api.Recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.IntegerField(choices=[(-1, '-1'), (1, '1')], default=0)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotrec_api.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
