# Generated by Django 2.2.1 on 2019-06-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='id',
        ),
        migrations.AddField(
            model_name='thing',
            name='uuid',
            field=models.CharField(default=0, max_length=128, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
