# Generated by Django 2.2.1 on 2019-10-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0002_auto_20191008_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='invoke_rec',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
