# Generated by Django 2.2.1 on 2019-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0002_auto_20190721_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='id',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000-0-0', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='uuid',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
        ),
    ]
