# Generated by Django 2.2.1 on 2019-06-02 14:26

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0002_auto_20190602_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='major_id',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='minor_id',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
