# Generated by Django 2.2.1 on 2019-07-28 09:10

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0002_auto_20190728_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=mptt.fields.TreeManyToManyField(blank=True, to='iotrec_api.Category'),
        ),
    ]
