# Generated by Django 2.2.1 on 2019-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0003_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nr_of_items_flat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='nr_of_items_recursive',
            field=models.IntegerField(default=0),
        ),
    ]
