# Generated by Django 2.2.1 on 2019-07-22 20:47

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0003_auto_20190721_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
    ]
