# Generated by Django 2.2.1 on 2019-07-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0004_thing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
