# Generated by Django 2.2.1 on 2019-10-02 16:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0004_auto_20190930_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default='00000000-0000-0000-0000-000000000000', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('invoke_rec', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotrec_api.Thing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default='00000000-0000-0000-0000-000000000000', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotrec_api.Recommendation')),
            ],
        ),
    ]
