# Generated by Django 2.2.1 on 2019-10-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0004_auto_20191016_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='value',
            field=models.IntegerField(choices=[(-1, '-1'), (1, '1')], default=0),
        ),
    ]
