# Generated by Django 2.2.1 on 2019-10-24 14:47

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import iotrec_api.utils.context


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0006_auto_20191024_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='weather_raw',
            field=enumchoicefield.fields.EnumChoiceField(enum_class=iotrec_api.utils.context.WeatherType, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='crowdedness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crowdedness', to='training.ContextFactorValue'),
        ),
        migrations.AlterField(
            model_name='context',
            name='time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_of_day', to='training.ContextFactorValue'),
        ),
    ]
