# Generated by Django 2.2.1 on 2019-10-27 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import iotrec_api.utils.analyticsevent


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0009_auto_20191027_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('type', enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=iotrec_api.utils.analyticsevent.AnalyticsEventType, max_length=9, null=True)),
                ('value', models.FloatField(default=0)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iotrec_api.Recommendation')),
                ('thing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iotrec_api.Thing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
