# Generated by Django 2.2.1 on 2019-10-03 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0009_auto_20191002_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.UUIDField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.UUIDField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='id',
            field=models.CharField(default=None, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('99985837-25b4-4a8c-8eb3-ea2947328b8d')),
        ),
    ]
