# Generated by Django 2.2.1 on 2019-10-03 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0010_auto_20191003_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
