# Generated by Django 2.2.1 on 2019-10-31 17:54

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0010_analyticsevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='major_id',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='minor_id',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='uuid',
        ),
        migrations.AddField(
            model_name='thing',
            name='eddystone_instance_id',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='eddystone_namespace_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='ibeacon_major_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='thing',
            name='ibeacon_minor_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='thing',
            name='ibeacon_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
