# Generated by Django 2.2.1 on 2019-10-04 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0011_auto_20191003_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
