# Generated by Django 2.2.1 on 2019-11-01 07:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0012_category_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.AlterField(
            model_name='preference',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='iotrec_api.Category'),
        ),
    ]
