# Generated by Django 2.2.1 on 2019-11-01 08:01

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0013_auto_20191101_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='iotrec_api.Category'),
        ),
    ]
