# Generated by Django 2.2.1 on 2019-10-04 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0013_auto_20191004_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preference',
            name='value',
            field=models.IntegerField(choices=[(-1, '-1'), (0, '0'), (1, '1')], default=0),
        ),
    ]
