# Generated by Django 2.2.1 on 2019-10-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0014_auto_20191004_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nr_of_items_flat',
        ),
        migrations.RemoveField(
            model_name='category',
            name='nr_of_items_recursive',
        ),
    ]
