# Generated by Django 2.2.1 on 2019-11-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0014_auto_20191101_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nr_of_items_recursive',
            field=models.IntegerField(default=0),
        ),
    ]
