# Generated by Django 2.2.1 on 2019-11-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0015_category_nr_of_items_recursive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsEvent',
        ),
    ]
