# Generated by Django 2.2.1 on 2019-10-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0016_auto_20191004_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='value',
            field=models.IntegerField(choices=[(-1, '-1'), (1, '1')], default=0),
        ),
    ]
