# Generated by Django 2.2.1 on 2019-11-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0005_auto_20191102_1356'),
        ('iotrec_api', '0016_delete_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.Scenario'),
        ),
    ]
