# Generated by Django 2.2.1 on 2019-11-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0006_auto_20191102_1357'),
        ('iotrec_api', '0017_thing_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='context_score',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.Experiment'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='locality_score',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='preference_score',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='stay',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.Experiment'),
        ),
    ]
