# Generated by Django 2.2.1 on 2019-11-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0021_iotrecsettings_evaluation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotrecsettings',
            name='training_active',
            field=models.BooleanField(default=True),
        ),
    ]
