# Generated by Django 2.2.1 on 2019-11-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0022_iotrecsettings_training_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='length_of_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='length_of_trip', to='training.ContextFactorValue'),
        ),
        migrations.AlterField(
            model_name='context',
            name='temperature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature', to='training.ContextFactorValue'),
        ),
        migrations.AlterField(
            model_name='context',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather', to='training.ContextFactorValue'),
        ),
    ]
