# Generated by Django 2.2.1 on 2019-11-16 12:50

from django.db import migrations
import enumchoicefield.fields
import iotrec_api.utils.context


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0023_auto_20191116_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='crowdedness_raw',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=iotrec_api.utils.context.CrowdednessType, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='time_of_day_raw',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=iotrec_api.utils.context.TimeOfDayType, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='weather_raw',
            field=enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=iotrec_api.utils.context.WeatherType, max_length=6, null=True),
        ),
    ]
