# Generated by Django 2.2.1 on 2019-11-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotrec_api', '0024_auto_20191116_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='context',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='iotrec_api.Context'),
        ),
    ]
