"""
Django settings for iotrec project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import datetime
import os

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'iotrec_api',
    'rest_framework',
    'corsheaders',
    'location_field.apps.DefaultConfig',
    'mptt',
    'training',
    'bootstrap4',
    'django.contrib.sites',
    'chroniker',
    'evaluation'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iotrec.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['iotrec/training/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'iotrec_api.context_processors.iotrec_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'iotrec.wsgi.application'

AUTH_USER_MODEL = 'iotrec_api.User'

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


#PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'iotrec_api.permissions.IsSignupOrIsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

CORS_ORIGIN_WHITELIST = (
    'http://localhost:3000',
)

JWT_AUTH = {
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'iotrec.utils.my_jwt_response_handler',
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=31536000) # one year
}

LOCATION_FIELD = {
    'search.provider': 'nominatim',
    'map.provider': 'openstreetmap',
    'provider.openstreetmap.max_zoom': 18
}

MPTT_ADMIN_LEVEL_INDENT = 20

DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000

BOOTSTRAP4 = {
    "css_url": {
        "href": "/static/css/bootstrap.min.css"
    },
    "javascript_url": {
        "url": "/static/js/bootstrap.bundle.min.js"
    },
    "jquery_url": {
        "url": "/static/js/jquery-3.4.1.min.js"
    },
    "popper_url": {
        "url": ""
    }
}

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'
MEDIA_URL = '/media/'