# Generated by Django 2.2.1 on 2019-09-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_referencething_indoorslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencething',
            name='indoorsLocation',
            field=models.BooleanField(default=True),
        ),
    ]
