# Generated by Django 2.2.1 on 2019-09-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_referencething_indoorslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencething',
            name='display_title',
            field=models.CharField(default='New Thing', max_length=128),
        ),
        migrations.AlterField(
            model_name='referencething',
            name='title',
            field=models.CharField(default='newThing', max_length=128),
        ),
    ]
