# Generated by Django 2.2.1 on 2019-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20190919_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextfactor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contextfactorvalue',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
