# Generated by Django 2.2.1 on 2019-09-30 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20190927_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencething',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='traininguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traininguser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
