# Generated by Django 2.2.1 on 2019-10-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20190930_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('value', models.FloatField(default=0, editable=False)),
                ('context_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.ContextFactor')),
                ('context_factor_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.ContextFactorValue')),
                ('reference_thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.ReferenceThing')),
            ],
        ),
    ]
