# Generated by Django 2.2.1 on 2019-10-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20191024_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextfactorvalue',
            name='title',
            field=models.CharField(default='factorValue', editable=False, max_length=128),
        ),
    ]
