# Generated by Django 2.2.1 on 2019-10-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20191024_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contextfactor',
            old_name='active',
            new_name='active_in_training',
        ),
        migrations.RenameField(
            model_name='contextfactorvalue',
            old_name='active',
            new_name='active_in_training',
        ),
        migrations.AddField(
            model_name='contextfactor',
            name='active_in_prediction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contextfactorvalue',
            name='active_in_prediction',
            field=models.BooleanField(default=True),
        ),
    ]
